### ISSUE TITLE
Smart Agent Crash

### ISSUE THREAD

**Issue by maximusvladimir** [AdditionalPylons2017/StarcraftAI#7]
```
Traceback (most recent call last):
  File "D:/Projects/StarcraftAI/launcher.py", line 132, in <module>
    if  __name__ =='__main__':main()
  File "D:/Projects/StarcraftAI/launcher.py", line 126, in main
    run_thread(mod, mapFile, getopts(args))
  File "D:/Projects/StarcraftAI/launcher.py", line 47, in run_thread
    run_loop.run_loop([agent], env, args["max_agent_steps"])
  File "D:\Python\lib\site-packages\pysc2\env\run_loop.py", line 41, in run_loop
    for agent, timestep in zip(agents, timesteps)]
  File "D:\Python\lib\site-packages\pysc2\env\run_loop.py", line 41, in <listcomp>
    for agent, timestep in zip(agents, timesteps)]
  File "D:\Projects\StarcraftAI\agents\learning_agent.py", line 206, in step
    return actions.FunctionCall(_ATTACK_MINIMAP, [_NOT_QUEUED, (attack_pos[0], attack_pos[1])])
UnboundLocalError: local variable 'attack_pos' referenced before assignment
```

**Comment by BeauJDMiller** [comment]
This error has been fixed.
